import { BrainCircuit, Target, TrendingDown } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Panel } from '../components/Panel';
import { recentLaps } from '../data/mock';

const data = recentLaps.slice().reverse().map((x, i) => ({ lap: x.lap, actual: 80.6 + i * 0.08 + Math.sin(i) * .22, predicted: 80.7 + i * 0.06 + Math.cos(i) * .16 }));
export default function Forecast() {
  return <div className="page-stack"><div className="page-heading"><div><h1>Forecast</h1><p>Forward-looking lap pace with uncertainty and leakage-safe inputs.</p></div><button className="primary-btn">Run forecast</button></div><div className="two-col"><Panel title="Next-lap trajectory" icon={<Target size={17} />}><div className="big-chart"><ResponsiveContainer width="100%" height={360}><AreaChart data={data}><defs><linearGradient id="pred" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ef4b50" stopOpacity={.25}/><stop offset="1" stopColor="#ef4b50" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#1f262d" vertical={false}/><XAxis dataKey="lap" tick={{fill:'#81909c'}}/><YAxis domain={[80,82]} tick={{fill:'#81909c'}}/><Tooltip contentStyle={{background:'#10161c',border:'1px solid #28313a'}}/><Area dataKey="predicted" stroke="#ef4b50" fill="url(#pred)"/><Line dataKey="actual" stroke="#e7eef4" dot={false}/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Forecast contract" icon={<BrainCircuit size={17} />}><div className="detail-list"><div><span>Target</span><strong>Lap N+1 residual pace</strong></div><div><span>Context</span><strong>5 previous laps</strong></div><div><span>Primary model</span><strong>RaceShift FFR</strong></div><div><span>Calibration</span><strong>80% quantile interval</strong></div><div><span>Validation</span><strong>Season-forward split</strong></div></div><div className="callout"><TrendingDown size={18}/><div><strong>No target leakage</strong><p>Inputs are restricted to information available at the end of lap N.</p></div></div></Panel></div></div>;
}
